language: java
jdk:
 - openjdk8
before_install:
 - chmod +x mvnw
services:
  - postgresql
before_script:
  - psql -c 'create database ponto_eletronico;' -U postgres
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5434