language: java
jdk:
 - openjdk8
before_install:
 - chmod +x mvnw
services:
  - postgresql
before_script:
  - psql -c 'create database ponto_eletronico;' -U postgres
addons:
  postgresql: "9.4"
env:
  global:
  - PGPORT=5434